name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupère le code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installe Java et Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Compile le projet
      - name: Build with Maven
        run: mvn clean install

      # Lance les tests
      - name: Run tests
        run: mvn test

      # Construit l'image Docker
      - name: Build Docker image
        run: docker build -t pipeline-example:latest .

      #Pousse l'image sur Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag pipeline-example:latest zarrad89/pipeline-example:latest

      - name: Push Docker image
        run: docker push zarrad89/pipeline-example:latest